// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckhxymywwvvacsnvobpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNraHh5bXl3d3Z2YWNzbnZvYnBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzY0MTYsImV4cCI6MjA2MDAxMjQxNn0.hYTWynYI00lhcR8OguKZwj8syapgzECm3S41eGKVW7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);